modLoader = "javafml"
loaderVersion = "[44,)"
issueTrackerURL = "https://github.com/MrEluzium/Linkage/issues"
license = "LGPL-3.0-only"

[[mods]]
modId = "linkage"
version = "${version}"
displayName = "Linkage"
authors = "Elzzz"
description = "Look mom I'm a minecraft modder!"
logoFile = "icon.png"

[[dependencies.linkage]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.linkage]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"